name: Draft PR Description
on:
  pull_request:
    types: [synchronize, opened, reopened, edited]

jobs:
  change-description:
    runs-on: ubuntu-latest
    name: Draft PR Description
    steps:
      - name: Add Draft PR description
        uses: fluxinc/gpt-auto-pr-description-action@master
        with:
          trigger-word: "ai-draft"
          github-token: ${{ secrets.TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}
          openai-token: ${{ secrets.OPENAI_API_KEY }}